export const imgs = {
    welcome: require("../assets/welcome.png"),
    apple: require("../assets/apple.png"),
    google: require("../assets/google.png"),
    facebook: require("../assets/facebook.png"),
    arleft: require("../assets/ar-left.png"),
    pdf: require("../assets/pdf.png"),
    user: require("../assets/user.png"),
    bell: require("../assets/bell.png"),
    bars: require("../assets/bars.png"),
    search: require("../assets/search.png"),
    company: require('../assets/company.png'),
    bag: require("../assets/bag.png"),
    home: require("../assets/home.png"),
    settings: require("../assets/settings.png"),
}